import type { PublicKey } from "@solana/web3.js";

export type SandboxKind = "magicblock" | "surfpool";

export interface FuzzConfig {
  programId: PublicKey;
  sandbox: SandboxKind;
  budgetTx: number;
  parallelism: number;
  reportDir: string;
  payerKeypairPath: string;
}

export interface Snapshot {
  programId: PublicKey;
  programData: Buffer;
  // Accounts owned by the program at snapshot time, plus any external
  // accounts referenced by their data (oracles, mints, token accounts).
  accounts: SnapshotAccount[];
  slot: bigint;
  capturedAtMs: number;
}

export interface SnapshotAccount {
  pubkey: PublicKey;
  owner: PublicKey;
  lamports: bigint;
  data: Buffer;
  executable: boolean;
}

// A live private execution environment provisioned for one fuzz run.
// Both MagicBlock Private ER and the Surfpool fallback implement this shape.
export interface Sandbox {
  kind: SandboxKind;
  rpcUrl: string;
  // The validator handling our txs. Populated for MagicBlock (the closest
  // ER validator the router selected); undefined for surfpool (the local
  // box itself is the validator).
  validator?: PublicKey;
  // Tearing down releases per-session resources. For MagicBlock this is
  // a no-op at the connection layer — the lease is per-account-delegation,
  // and the fuzz loop is responsible for undelegating any state it
  // delegated during the run.
  teardown(): Promise<void>;
}

export interface Finding {
  id: string;
  invariant: InvariantId;
  severity: "critical" | "high" | "medium" | "low";
  title: string;
  evidenceTxs: string[];
  // Human-readable explanation, generated by the agent's brain.
  narrative: string;
}

export type InvariantId = "INV-1" | "INV-2" | "INV-3";

export interface InvariantViolation {
  invariant: InvariantId;
  message: string;
  observed: unknown;
  expected: unknown;
}

export interface FuzzReport {
  config: Omit<FuzzConfig, "payerKeypairPath">;
  // The validator that actually executed the run, if known. For the
  // MagicBlock path this is the ER validator the router pinned us to;
  // recording it in the report makes it auditable that a Surfpool-only
  // run didn't accidentally headline as a Private-ER demo.
  validator?: string;
  snapshotSlot: bigint;
  startedAtMs: number;
  endedAtMs: number;
  txsAttempted: number;
  txsLanded: number;
  findings: Finding[];
}
