import type { PublicKey } from "@solana/web3.js";

export type SandboxKind = "magicblock" | "surfpool";

export interface FuzzConfig {
  programId: PublicKey;
  sandbox: SandboxKind;
  budgetTx: number;
  parallelism: number;
  reportDir: string;
  payerKeypairPath: string;
}

export interface Snapshot {
  programId: PublicKey;
  programData: Buffer;
  // Accounts owned by the program at snapshot time, plus any external
  // accounts referenced by their data (oracles, mints, token accounts).
  accounts: SnapshotAccount[];
  slot: bigint;
  capturedAtMs: number;
}

export interface SnapshotAccount {
  pubkey: PublicKey;
  owner: PublicKey;
  lamports: bigint;
  data: Buffer;
  executable: boolean;
}

// A live private execution environment provisioned for one fuzz run.
// Both MagicBlock Private ER and the Surfpool fallback implement this shape.
export interface Sandbox {
  kind: SandboxKind;
  rpcUrl: string;
  // Tearing down deletes all state — nothing escapes to mainnet.
  teardown(): Promise<void>;
}

export interface Finding {
  id: string;
  invariant: InvariantId;
  severity: "critical" | "high" | "medium" | "low";
  title: string;
  evidenceTxs: string[];
  // Human-readable explanation, generated by the agent's brain.
  narrative: string;
}

export type InvariantId = "INV-1" | "INV-2" | "INV-3";

export interface InvariantViolation {
  invariant: InvariantId;
  message: string;
  observed: unknown;
  expected: unknown;
}

export interface FuzzReport {
  config: Omit<FuzzConfig, "payerKeypairPath">;
  snapshotSlot: bigint;
  startedAtMs: number;
  endedAtMs: number;
  txsAttempted: number;
  txsLanded: number;
  findings: Finding[];
}
